export const SET_ENTRY = "SET_ENTRY";
export const ADD_ENTRY = "ADD_ENTRY";
export const SET_MEAL = "SET_MEAL";
export const SET_BREAKDOWN = "SET_BREAKDOWN";
export const ADD_ENTRY_SUCCESS = "ADD_ENTRY_SUCCESS";
export const ADD_ENTRY_FAIL = "ADD_ENTRY_FAIL";
export const FOOD_SEARCH = "FOOD_SEARCH";
export const DELETE_ENTRY = "DELETE_ENTRY";
export const INIT_ENTRIES = "INIT_ENTRIES";
export const FETCH_ENTRIES_FAILED = "FETCH_ENTRIES_FAILED";
export const SET_BREAKFAST = "SET_BREAKFAST";
export const SET_LUNCH = "SET_LUNCH";
export const SET_DINNER = "SET_DINNER";
export const SET_SNACK = "SET_SNACK";
export const ADD_BREAKFAST_ENTRY = "ADD_BREAKFAST_ENTRY";
export const ADD_LUNCH_ENTRY = "ADD_LUNCH_ENTRY";
export const ADD_DINNER_ENTRY = "ADD_DINNER_ENTRY";
export const ADD_SNACK_ENTRY = "ADD_SNACK_ENTRY";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_CAL_GOAL = "SET_CAL_GOAL";
export const SET_INFO_START = "SET_INFO_START";
export const SET_INFO_SUCCESS = "SET_INFO_SUCCESS";
export const SET_INFO_FAIL = "SET_INFO_FAIL";
export const FETCH_INFO_START = "FETCH_INFO_START";
export const FETCH_INFO_SUCCESS = "FETCH_INFO_SUCCESS";
export const FETCH_INFO_FAIL = "FETCH_INFO_FAIL";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const UPDATE_CUR_TAB = "UPDATE_CUR_TAB";
export const SET_TAB_STATUS = "SET_TAB_STATUS";
export const SET_PAGE = "SET_PAGE";
